<a href="https://colab.research.google.com/github/pjloor/machinelearning-pedroloor/blob/main/Exercises_about_Numpy_library_PedroLoor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PRIMERA PARTE**

In [14]:
import numpy as np

aux=np.array([1,2,4])
print(aux)
print('-----------')
# Shape no ayuda a sabes las dimención o froma de la matriz
print(aux.shape)

aux=np.array([[1,2,4],[1,2,4]])
print(aux.shape)
print(aux)
print('-----------')
print(type(aux))

# los crea matrices con únicamente 0
x=np.zeros((4,4))
print('-----------')
print(x)

#full crea matrices con un valor constante en este caso 5
x=np.full((4,4),5)
print('-----------')
print(x)

# eyer crea una matriz de identificación ya que completa la matriz con 0 y en la parte principal lo completa con 1
x=np.eye(4,4)
print('-----------')
print(x)

# Ones se utiliza para crear un array (o matriz) de una forma específica, llena de unos
x=np.ones((4,4))
print('-----------')
print(x)

print(x.shape)

[1 2 4]
-----------
(3,)
(2, 3)
[[1 2 4]
 [1 2 4]]
-----------
<class 'numpy.ndarray'>
-----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-----------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [15]:
# ramdom.random se utiliza para generar un número decimal aleatorio en el rango que es esta caso es de (3,3)
x=10*np.random.random((3,3))
print(x)

[[4.13017433 4.75015538 0.99227126]
 [4.99411136 8.34369523 5.45913279]
 [2.24338153 7.09628873 2.00013803]]


In [16]:
print(x[:2,:2])

[[4.13017433 4.75015538]
 [4.99411136 8.34369523]]


In [17]:
print(x[:2,1:3])

[[4.75015538 0.99227126]
 [8.34369523 5.45913279]]


In [18]:
print(x[1,1])

8.343695228635795


In [19]:
print(x[2,2])

2.0001380301758322


In [20]:
# ramdom.random se utiliza para generar un número decimal aleatorio en el rango que es esta caso es de (3,3)
x=10*np.random.random((3,3))
print(x)

[[2.50436726 5.74599595 2.93131979]
 [1.01266886 3.20700095 4.62037053]
 [5.10859929 2.66059819 0.12279166]]


In [21]:
# mask se puede utilizar con arrays o matrices para realizar operaciones condicionales.
mask=x>5
print(x[mask])

[5.74599595 5.10859929]


In [22]:
#filter es una función incorporada que se utiliza para filtrar elementos de una secuencia entre un rango
filter=(x>=2)&(x<=4)
print(x[filter])

[2.50436726 2.93131979 3.20700095 2.66059819]


In [23]:
#filter es una función incorporada que se utiliza para filtrar elementos de una secuencia entre un rango
filter=(x>=2)&(x<=4)
print(x[filter])

[2.50436726 2.93131979 3.20700095 2.66059819]


In [24]:
# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,5)
integer_array=np.random.randint(0,5,(4,4))
print(integer_array)

[[0 0 1 1]
 [2 4 4 3]
 [4 1 2 1]
 [3 0 1 0]]


**SEGUNDA PARTE**



In [25]:
import numpy as np
# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,10)
a=np.random.randint(0,10,(3,4))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
# se imprime la matriz A
print(a)
print("MATRIZ B")
# se imprime la matriz b
print(b)
print("SUMANDO")
# se imprime una matriz sumando la matriz a+b
print(a+b)
print("RESTANDO")
# se imprime una matriz restando la matriz a-b
print(a-b)
print("MULTIPLICANDO")
# se imprime una matriz multiplicando la matriz a*b
print(a*b)
print("___________")

# add se utiliza para realizar la suma de dos arrays o matrices de elemento por elemento.
print(np.add(a,b))
print("___________")

# multiply se utiliza para realizar la multiplicaciones de dos arrays o matrices de elemento por elemento.
print(np.multiply(a,b))
print("___________")

# divide se utiliza para realizar la divisiones de dos arrays o matrices de elemento por elemento.
print(np.divide(a,b))
print("___________")


MATRIZ A
[[2 4 3 6]
 [2 2 0 6]
 [1 4 4 2]]
MATRIZ B
[[6 9 3 1]
 [0 5 0 3]
 [1 1 9 3]]
SUMANDO
[[ 8 13  6  7]
 [ 2  7  0  9]
 [ 2  5 13  5]]
RESTANDO
[[-4 -5  0  5]
 [ 2 -3  0  3]
 [ 0  3 -5 -1]]
MULTIPLICANDO
[[12 36  9  6]
 [ 0 10  0 18]
 [ 1  4 36  6]]
___________
[[ 8 13  6  7]
 [ 2  7  0  9]
 [ 2  5 13  5]]
___________
[[12 36  9  6]
 [ 0 10  0 18]
 [ 1  4 36  6]]
___________
[[0.33333333 0.44444444 1.         6.        ]
 [       inf 0.4               nan 2.        ]
 [1.         4.         0.44444444 0.66666667]]
___________


<ipython-input-25-05e0c2dd3210>:32: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))
<ipython-input-25-05e0c2dd3210>:32: RuntimeWarning: invalid value encountered in divide
  print(np.divide(a,b))


In [26]:
# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,10)
a=np.random.randint(0,10,(2,3))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
print(a)
print("MATRIZ B")
print(b)
print("___________")

# dot son multiplica las matrices
print(np.dot(a,b))

MATRIZ A
[[0 4 4]
 [3 6 5]]
MATRIZ B
[[6 5 5 6]
 [8 7 4 1]
 [2 9 6 6]]
___________
[[ 40  64  40  28]
 [ 76 102  69  54]]


In [27]:
a=np.random.randint(0,10,(3,3))
print(a)
print("___________")
# a.T intercambia las filas por columnas
print(a.T)

[[1 5 7]
 [7 4 6]
 [2 0 9]]
___________
[[1 7 2]
 [5 4 0]
 [7 6 9]]


In [28]:
a=np.random.randint(0,10,(4,3))
print(a)
print("___________")

b=np.array([1,0,2])
print(b)
print("___________")

# se crea una nueva matriz  utilizando la matriz A y B
c=np.empty_like(a)
print(c)
print("___________")
x=a+b

print(np.empty_like(x))

[[5 5 5]
 [9 1 3]
 [9 4 7]
 [9 3 8]]
___________
[1 0 2]
___________
[[6 5 5]
 [6 8 7]
 [4 1 2]
 [9 6 6]]
___________
[[98980193123176              0              2]
 [             1              0              2]
 [             1              0              2]
 [             1              0              2]]


In [29]:
# FOR se utiliza para realizar un blucle y tiene un rango
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print("___________")


print(b)
print("___________")


print(c)
print("___________")

[[5 5 5]
 [9 1 3]
 [9 4 7]
 [9 3 8]]
___________
[1 0 2]
___________
[[ 6  5  7]
 [10  1  5]
 [10  4  9]
 [10  3 10]]
___________


In [30]:
b=np.array([1,2,3])
print(b)
print("___________")

# tile se utiliza para replicar la matrices en esta caso se replica la matriz B pero con un rango de 6 veces
x=np.tile(b,(6,1))
print(x)

[1 2 3]
___________
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
a=np.random.randint(20,31,(6,6))
print(a)
print("___________")

print("PROMEDIOS COMPLETOS")
# Mean se utiliza para crear el promedio de la matriz
aux1=np.mean(a)
print(aux1)

print("___________")
print("PROMEDIOS POR FILAS")
# Mean se utiliza para crear el promedio de la matriz pero ahora por fila en este caso la fila 1
aux2=np.mean(a,axis=1)
print(aux2)

[[20 29 27 27 29 27]
 [23 26 25 29 21 25]
 [25 26 20 29 25 27]
 [29 20 23 30 30 26]
 [21 26 22 30 29 26]
 [21 28 24 20 26 27]]
___________
PROMEDIOS COMPLETOS
25.5
___________
PROMEDIOS POR FILAS
[26.5        24.83333333 25.33333333 26.33333333 25.66666667 24.33333333]
