<a href="https://colab.research.google.com/github/pjloor/machinelearning-pedroloor/blob/main/Pedro_Loor_Copia_de_NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
# Import numpy as np and see the version
import numpy as np
# your code here
pass


In [ ]:
# Create a 1D array of numbers from 0 to 9
# your code here
pass
array = list(range(10))
print(array)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
pass
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print(random_vector)

[0.61013808 0.85751009 0.15529042 0.44816874 0.00490569 0.89962424
 0.93996378 0.91644351 0.01299375 0.18390973]


In [ ]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
pass
number_8 = arr[1, 2]

print(number_8)

8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
pass
subset = arr[2:5]

print(subset)

[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
pass
last_four = arr[-4:]

print(last_four)

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
# your code here
pass
true_array = np.ones((3, 3), dtype=bool)

print(true_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extract all odd numbers from arr
# your code here
pass
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to extract odd numbers
odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
pass
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)
pass
vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector using slicing
reversed_vector = vector[::-1]

print(reversed_vector)

[5 4 3 2 1]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
pass
min_value = np.min(array)
max_value = np.max(array)

print("Array:")
print(array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Array:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Minimum value: 0
Maximum value: 9


In [ ]:
# Create a 3x3x3 array with random values
pass
array = np.random.rand(3, 3, 3)

print(array)

[[[0.16376479 0.20290355 0.86993769]
  [0.60862989 0.46180211 0.75607949]
  [0.49151639 0.19060108 0.65929471]]

 [[0.69366733 0.88007169 0.06022132]
  [0.59818729 0.11455955 0.25550461]
  [0.78339308 0.60461395 0.67402734]]

 [[0.10690529 0.59163534 0.79142979]
  [0.81311195 0.13937369 0.4250239 ]
  [0.31839095 0.18756425 0.32164491]]]


In [ ]:
# Replace all odd numbers in arr with -1
# your code here
pass
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a boolean mask for odd numbers
mask = arr % 2 == 1

# Replace odd numbers with -1 using the mask
arr[mask] = -1

print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Create an array of type float
pass
float_array = np.array([1.0, 2.5, 3.7, 4.2], dtype=float)

print(float_array)

[1.  2.5 3.7 4.2]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
pass
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to have 2 rows
new_array = original_array.reshape(2, -1)

print(new_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
pass
common_values = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print("Common Values:", common_values)

Z1: [7 8 2 0 1 4 4 0 9 5]
Z2: [2 5 4 1 4 9 0 2 2 5]
Common Values: [0 1 2 4 5 9]


In [ ]:
#  Consider two random array A and B, check if they are equal


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

pass
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Array A: [0 1 0 1 0]
Array B: [0 0 1 0 1]
Arrays A and B are not equal.


In [ ]:
# Stack arrays a and b vertically
# your code here
pass
# Create two example arrays a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays a and b vertically
result = np.vstack((a, b))

print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Stack the arrays a and b horizontally.
# your code here
pass
# Create two example arrays a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays a and b horizontally
result = np.hstack((a, b))

print(result)

[1 2 3 4 5 6]


In [ ]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
# pass
subset = tmp[5:11]

print(subset)

[ 5  6  7  8  9 10]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
#a = np.array([5, 7, 9, 8, 6, 4, 5])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
##> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)

def pair_max(x, y):
    """Get the maximum of two items"""
    return np.maximum(x, y)

# Example scalars
scalar_x = 5
scalar_y = 6

# Example arrays
array_a = np.array([5, 7, 9, 8, 6, 4, 5])
array_b = np.array([6, 3, 4, 8, 9, 7, 1])

# Apply the pair_max function to scalars
result_scalar = pair_max(scalar_x, scalar_y)
print("Scalar result:", result_scalar)

# Apply the pair_max function to arrays (broadcasting)
result_array = pair_max(array_a, array_b)
print("Array result:")
print(result_array)


Scalar result: 6
Array result:
[6 7 9 8 9 7 5]


In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
pass

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

# Create a 5x3 array with random decimal numbers between 5 and 10
random_array = np.random.uniform(5, 10, (5, 3))

print(random_array)

[[5.03943024 9.2486458  7.38461606]
 [7.60669731 6.36804367 8.74403935]
 [7.77609651 6.58277792 7.22593589]
 [8.81042335 5.70912998 8.22931604]
 [7.21255422 6.17471484 5.47789722]]
